### ISSUE TITLE
Tutorial template

### ISSUE THREAD

**Issue by fabric-and-ink** [commercialhaskell/stack-templates#124]
Please add a *tutorial* template. Show how to add packages and do some simple file reading/printing. Demonstrate how to setup a small unit test framework. Take a total beginner (like me) by the hand.  Display a message right after installing *stack* that there is a  tutorial waiting.

**Comment by mpilgrem** [comment]
I am going to close this issue because the online guide to the Haskell Tool Stack has a relatively lengthy [guide](https://docs.haskellstack.org/en/stable/GUIDE/) that does seek to take a total beginner by the hand through most of Stack's functionality. The length of the guide illustrates the challenge of doing something similar by means of a Stack project template.

If the current user guide is lacking it would be a better investment to improve the guide.
