### ISSUE TITLE
Are there any gui templates such using gtk+

### ISSUE THREAD

**Issue by gdennie** [commercialhaskell/stack-templates#134]
It would be good to eventually enable cross platform applications, in particular Linux to Windows and Mac. It seems a proper GUI template would be a good first step, perhaps capitalizing on existing cross platform frameworks such as GTK+. I am surprise there isn't already such a template. However, I am new to Haskell expect there is a good though unfathomable reason. ;)

**Comment by mpilgrem** [comment]
The complexity of GTK3 or GTK4 means that it may be better suited to tutorial-type content - such as the [wiki of haskell-gi](https://github.com/haskell-gi/haskell-gi/wiki), which has helped me in the past - rather than a Stack project template. One of the challenges, particularly on Windows, is setting up the underlying libraries so that the Haskell code/executable can find what it needs (and, mostly recently with GTK4, to avoid a conflict between MSYS2 and versions of GHC before 9.4.1). A Stack project template (which needs to be cross-platform) is likely not the best mechanism to explain that.

In any event, in the interim, this repository has announced that it is not accepting new templates. So I will close this issue.
