### ISSUE TITLE
ghcjs template broken out of the box

### ISSUE THREAD

**Issue by silky** [commercialhaskell/stack-templates#15]
running today, with `stack --version`

```
Version 0.1.6.0, Git revision e22271f5ce9afa2cb5be3bad9cafa392c623f85c (2313 commits) x86_64
```

starting a new project with template `ghcjs` fails. stack can't find a buildplan. i tried `stack init --solver` in the folder and i get

```
⚡ 08:23 PM noon ∈ simutron5000@master>stack init --solver                            1 ↵
Writing default config file to: /home/noon/dev/simutron5000/simutron5000/stack.yaml
Basing on cabal files:
- /home/noon/dev/simutron5000/simutron5000/simutron5000.cabal

Asking cabal to calculate a build plan, please wait
Running /home/noon/.cabal/bin/cabal --config-file=/tmp/cabal-solver21621/cabal.config install --enable-tests --enable-benchmarks -v --dry-run --only-dependencies --reorder-goals --max-backjumps=-1 --package-db=clear --package-db=global /home/noon/dev/simutron5000/simutron5000/ exited with ExitFailure 1
'/usr/bin/alex' '--version'
'/home/noon/.cabal/bin/c2hs' '--numeric-version'
'/home/noon/.cabal/bin/cpphs' '--version'
'/usr/bin/gcc' '-dumpversion'
'/usr/local/bin/haddock' '--version'
'/home/noon/.cabal/bin/happy' '--version'
'/usr/local/bin/hpc' 'version'
looking for tool hsc2hs near compiler in /usr/local/bin
found hsc2hs in /usr/local/bin/hsc2hs
'/usr/local/bin/hsc2hs' '--version'
'/home/noon/.cabal/bin/HsColour' '-version'
'/usr/local/bin/ghc' '-c' '/tmp/21640.c' '-o' '/tmp/21640.o'
'/usr/bin/ld' '-x' '-r' '/tmp/21640.o' '-o' '/tmp/21641.o'
'/usr/bin/pkg-config' '--version'
'/bin/tar' '--help'
Reading available packages...
Updating the index cache file...
Choosing modular solver.
Resolving dependencies...

cabal: Could not resolve dependencies:
trying: simutron5000-0.1.0.0 (user goal)
next goal: ghcjs-base (dependency of simutron5000-0.1.0.0)
Dependency tree exhaustively searched.
```

am i missing something?

**Comment by snoyberg** [comment]
Pinging @mgsloan

**Comment by mgsloan** [comment]
The issue here is that `stack init` does not check if the projects look like GHCJS projects.  I can see a few ways to resolve this:

* Punt on `stack init` doing anything special for GHCJS, unless maybe you pass it a flag.  Perhaps include a stack.yaml file with the template.

* Guess that GHCJS is needed if `ghcjs-base` or `ghcjs-prim` is a dependency, or when the cabal `impl(ghcjs)` condition is used somewhere.

* Do a proper analysis of the conditional cabal trees to properly handle cases where `impl(ghcjs)` is involved with `buildable`.  Seems like more trouble than it's worth.

* Pick a version of GHC and a version of GHCJS.  Use `resolvePackage` to handle all the cabal conditional stuff properly, and then consider a package to be "more buildable" for GHCJS if its library or executable is buildable with GHCJS but not with GHC.  The issue with this one is that we'd need to pick compiler versions, which would likely entail downloading `setup-info-2.yaml`.

**Comment by mpilgrem** [comment]
I am closing this issue as the pull request removing the confusing Stack project templates has now been merged.
