### ISSUE TITLE
templates with names identical to packages are broken

### ISSUE THREAD

**Issue by charles-cooper** [commercialhaskell/stack-templates#69]
To illustrate, one can create a new `servant` project
`stack new servant`
And then modify `app/Main.hs` to `import Servant.API`. Stack / cabal / ghc will complain that Servant.API was not found. The reason being that the cabal file (relevant bits below) references itself rather than the actual `servant` package.

Changing the project name from `servant` to `foobar` fixes the issue and cabal is able to resolve the dependency.

I'm not sure if this is by design or not but it definitely is confusing. At the very least the template should include a README which explains how the template is meant to be used.

```
__DATA__
ubuntu@ip-172-31-34-114:~/servant$ cat servant.cabal 
name:                servant
version:             0.1.0.0
synopsis:            Initial project template from stack
...
executable app
  hs-source-dirs:      app
  main-is:             Main.hs
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N
  build-depends:       base
                     , servant
  default-language:    Haskell2010

```

**Comment by mgsloan** [comment]
It's by design.  This way you can unpack a hackage package / clone from git, and instead use a locally modified version.  So, stack thinks you are defining a new version of the servant package.

Given that, I'm not sure we even want to have a warning about this case.  It might be helpful to make it clear in something like https://github.com/commercialhaskell/stack/issues/2393
